env:
  es2021: true
  node: true
extends:
  - standard-with-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
overrides: []
parserOptions:
  project: 'tsconfig.json'
  ecmaVersion: latest
  sourceType: module
rules: {
  semi: ['error', 'always'],
}
